version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: crud-with-auth
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:6.2
    volumes:
      - "./tmp/redis:/data"
    ports:
      - "6379:6379"

  postgres:
      image: postgres:latest
      container_name: postgres-oauth-test
      restart: always
      ports:
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
          # - $PWD/:/postgresql/data/:/var/lib/postgresql/data
          # - $PWD/:/postgresql/data/:/var/lib/postgresql/data
          - $PWD/:/postgresql/data/test/:/var/lib/postgresql/data
  # postgres:
  #   image: postgres:13.4
  #   ports:
  #     - "5433:5432"